### PR TITLE
[JENKINS-36875] Empty screen when creating new jobs

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-36875](https://issues.jenkins-ci.org/browse/JENKINS-36875)

There is an enconding issue.

@reviewbybees especially @aheritier

### CODE REVIEW

**Comment by aheritier** [comment]
Here is what I propose ( I cannot edit your PR)

```
ExternalJob.displayName=T\u00E2che externe
ExternalJob.Description=Ce type de t\u00E2che permet de suivre l''\u00E9xecution d''un process lanc\u00E9 en dehors de Jenkins, et ce, m\u00EAme sur une machine distante. \
Cela vous permet d'utiliser Jenkins comme tableau de bord de vos syst\u00E8mes automatis\u00E9s existant.\
cf <a href="http://wiki.jenkins-ci.org/display/JENKINS/Monitoring+external+jobs">la documentation pour plus de d\u00E9tails</a>.
```

**Comment by aheritier** [comment]
cc @batmat @alecharp and the french connection

**Comment by recena** [comment]
A preview:

jenkins-36875

**Comment by recena** [comment]
@aheritier I recommend to remove the link, I did that in the spanish translation. I don't like the idea to include HTML code in property file entries. In fact, the links are not working 😭

**Comment by aheritier** [comment]
ok @recena In that case we need to remove it from the EN version (this is where I copied it)

**Comment by recena** [comment]
@aheritier and @jenkinsci/code-reviewers, What do you think?

**Comment by daniel-beck** [comment]
To clarify, no links in item type descriptions work due to the chosen UI behavior? I.e. clicking the "link" will just select the item type?

**Comment by recena** [comment]
@daniel-beck No. You can add links in the item description but it seems the current implementation does not allow to click the links becasue the event is being handled by a specific function. I have to review it.

At any rate, I don't recommend to include HTML code in the item description.

**Comment by aheritier** [comment]
@recena Let's track this problem of link somewhere else but yes for now I prefer no link than a broken link (especialy if the problem comes from the Core/UI and not the plugin).

**Comment by recena** [comment]
@aheritier It seems it is [confirmed](https://issues.jenkins-ci.org/browse/JENKINS-36875?focusedCommentId=265161&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-265161) that this PR works.

**Comment by aheritier** [comment]
yes @recena 
Let's merge/release I think to have a quick fix ASAP (even if it should - for now - consider only few people)

**Comment by oleg-nenashev** [comment]
👍 BTW

**Comment by aheritier** [comment]
:bee:

**Pull request merged**
