### PR TITLE
Update parent POM and jenkins baseline for JDK11 compatibility

### PR DESCRIPTION
**Pull request by Vlatombe**
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by alecharp** [comment]
Is there any requirement to have this PR merge to say the plugin is compatible? There is no code change here.

**Comment by mikecirioli** [comment]
@alecharp i do not think it is strictly needed, the pom.xml change was done as part of our plugin review for JDK11

**Comment by Vlatombe** [comment]
It's only required for PCT to be successful when using JDK11.

**Comment by mikecirioli** [comment]
@alecharp @Vlatombe any objections to merging and releasing this?

**Comment by mikecirioli** [comment]
@jglick  can you merge/release this?

**Review by jglick — APPROVED** [review]

**Pull request merged**
